:doctitle: {_doctitle} - Tuple Fields

include::_toc.adoc[]

== Tuple Fields

As data stored in tuples moves through a pipe assembly, individual columns or
fields are added, removed, or modified in place as they pass through each pipe.

Tuple fields are manipulated through the use of the
[classname]+cascading.tuple.Fields+ class. Fields can be used to either declare
a given set of fields (like fields are declared on a class definition) or to
select a set of fields from another tuple. For example, if you declare a Tuple
has the following field names `[first, last]`, you can later select `[last]`
from the Tuple for use as an argument to an Operation. Equivalently, you can
select the second position with the ordinal `[1]` or the last position with the
ordinal `[-1]`.

Both [classname]+Each+ and [classname]+Every+ pipes process an input Tuple with
the following steps:

. The pipe selects fields from the input Tuple as arguments to the child
[classname]+Operation+ (Function ,Filter , Aggregator, or Buffer).

. The pipe receives results from the [classname]+Operation+.

. [classname]+Operation+ results are returned. The results can be a mix of
incoming Tuple values and Operation Tuple results.

This is achieved by providing new Fields instances that select or declare the
required field names or ordinals as appropriate. When selecting arguments for an
Operation, or the outgoing fields of the pipe, Cascading provides _Fields sets_,
a feature of the [classname]+Fields+ class that provides a sort of wildcard tool
for referencing sets of field values without declaring them specifically.

There are also cases where _Fields sets_ can be used when fields should be
declared. All these cases are described below.

TIP: To see _Fields sets_ in action, see the
<<ch16-operations.adoc#identity-function,Identity function documentation>>.

[[field-sets]]
=== Field Sets

These predefined Fields sets are constant values on the [classname]+Fields+
class. They can be used in many places where the [classname]+Fields+ class is
expected. They are:

Fields.ALL::

The [classname]+cascading.tuple.Fields.ALL+ constant is a wildcard that
represents all the current available fields.

include::_algebra-all.adoc[]

Fields.RESULTS::

The [classname]+cascading.tuple.Fields.RESULTS+ constant is used to represent
the field names of the current-operation return values. This Fields set can
only be used as an output selector on a pipe, causing the pipe to output a tuple
containing the operation results.

include::_algebra-results.adoc[]

Fields.REPLACE::

The [classname]+cascading.tuple.Fields.REPLACE+ constant is used as an output
selector to inline-replace values in the incoming tuple with the results of an
operation. This convenient Fields set allows operations to overwrite the value
stored in the specified field. The current operation must either specify the
identical argument selector field names used by the pipe, or use the
[classname]+ARGS+ Fields set.

include::_algebra-replace.adoc[]

Fields.SWAP::

The [classname]+cascading.tuple.Fields.SWAP+ constant is used as an output
selector to swap the operation arguments with its results. Neither the argument
and result field names, nor the size, need to be the same. This is useful for
when the operation arguments are no longer necessary and the result Fields and
values should be appended to the remainder of the input field names and Tuple.

include::_algebra-swap.adoc[]

Fields.ARGS::

The [classname]+cascading.tuple.Fields.ARGS+ constant is used to let a given
operation inherit the field names of its argument Tuple. This Fields set is a
convenience and is typically used when the Pipe output selector is
[classname]+RESULTS+ or [classname]+REPLACE+. It is specifically used by the
Identity function when coercing values from Strings to primitive types.

include::_algebra-replace.adoc[]

Fields.GROUP::

The [classname]+cascading.tuple.Fields.GROUP+ constant represents all the fields
used as the grouping key in the most recent grouping. If no previous grouping
exists in the pipe assembly, [classname]+GROUP+ represents all the current
field names.

include::_algebra-group.adoc[]

Fields.VALUES::

The [classname]+cascading.tuple.Fields.VALUES+ constant represents all the
fields not used as grouping fields in a previous Group. That is, if you have
fields _a_, _b_, and _c_, and group on _a_, [classname]+Fields.VALUES+
resolves to _b_ and _c_.

include::_algebra-values.adoc[]

Fields.UNKNOWN::

The [classname]+cascading.tuple.Fields.UNKNOWN+ constant is used when Fields
must be declared, but neither quantity nor names of the fields are known.
This allows for processing tuples of arbitrary length from an input source or
an operation.

NOTE: Use [classname]+cascading.tuple.Fields.UNKNOWN+ with caution.

include::_algebra-unknown.adoc[]

Fields.NONE::

The [classname]+cascading.tuple.Fields.NONE+ constant is used to specify no
fields. This constant is typically used as an argument selector for Operations
that do not process any tuples, like [classname]+cascading.operation.Insert+.

include::_algebra-none.adoc[]

TIP: The [classname]+cascading.tuple.Fields.NONE+ constant can also be used
when performing a join with [classname]+CoGroup+ or
[classname]+HashJoin+ when a full cross product is desired across all data. But
doing this type of join degrades performance.

[[field-algebra]]
=== Field Algebra

The chart below shows common ways to merge input and result fields for the
desired output fields. A few minutes with this chart may help clarify the
discussion of fields, tuples, and pipes. Also see
<<ch05-pipe-assemblies.adoc#each-every, Each and Every Pipes>> for details on
the different columns and their relationships to the [classname]+Each+
and [classname]+Every+ pipes and functions, aggregators, and buffers.

image:images/field-algebra.svg[align="center"]

[[field-typing]]
=== Field Typing

The Fields class can hold type information for each field, and the Cascading
planner can propagate that information from source Tap instances to downstream
Operations through to sink Tap instances.

This allows for:

* Taps to read and store type information for external systems and
  applications
* Error detection during joins (detecting non-comparable types)
* Enforcement of canonical representations within the Tuple (prevent a field
  from switching arbitrarily between String and Integer types)
* Pluggable coercion from one type to another type, even if either
  is not a Java primitive
* Much improved data serialization/network performance between map and reduce
  nodes, or between Tez vertices. *New in 3.1*

To declare types, simply pass type information to the Fields instance either
through the constructor or via a fluent API.

.Constructor
====
include::_fields-type-constructor.adoc[]
====

.Fluent
====
include::_fields-type-fluent.adoc[]
====

Note the first example uses [classname]+Long.class+, and the second
[classname]+long.class+. Since [classname]+Long+ is an object, we are letting
Cascading know that the null value can be set. If declared [classname]+long+ (a
primitive) then, null becomes zero.

In practice, typed fields can only be used when they declare the results of an
Operation or the input/output of a Scheme.

.Declaring typed results
====
include::_partials-compose.adoc[]
====

Here the type information serves two roles.

First, it allows a downstream consumer of the field value to know the type
maintained in the tuple.

Second, the SumBy subassembly now has a simpler API and can get the type
information it needs internally to perform the aggregation directly from the
Fields instance.

Note that the [classname]+TextDelimited+ and other [classname]+Scheme+ classes
should have any type information declared so it can be maintained by the
Cascading planner. Custom [classname]+Scheme+ types also have the opportunity to
read type information from any field or data sources they represent so it can be
passed to the planner during runtime.

[[field-coercion]]
=== Type Coercion

Type coercion is a means to convert one data type to another. For example,
parsing the Java [classname]+String+ "42" to the [classname]+Integer+ 42 would
be coercion. Or more simply, converting a [classname]+Long+ 42 to a
[classname]+Double+ 42.0. Cascading supports primitive type coercions natively
through the [classname]+cascading.tuple.coerce.Coercions+ class.

In practice, developers implicitly invoke coercions via the
[classname]+cascading.tuple.TupleEntry+ interface by requesting a
[classname]+Long+ or [classname]+String+ representation of a field, via
[code]+TupleEntry.getLong()+ or [code]+TupleEntry.getString()+, respectively.

Or when data is set on a [classname]+Tuple+ via [code]+TupleEntry.setLong()+ or
[code]+TupleEntry.setString()+, for example. If the field was declared as an
[classname]+Integer+, and [code]+TupleEntry.setString( "someField", "42" )+ was
called, the value of "someFields" will be coerced into its canonical form, 42.

To create custom coercions, the [classname]+cascading.tuple.type.CoercibleType+
interface must be implemented, and instances of [classname]+CoercibleType+ can
be used as the [classname]+Type+ accepted by the Fields API as
[classname]+CoercibleType+ extends [classname]+java.lang.reflect.Type+ (as does
[classname]+java.lang.Class+).

Cascading provides a [classname]+cascading.tuple.type.DateType+ implementation
to allow for coercions between date strings and the [classname]+Long+ canonical
type.

.Date type
====
include::_fields-date-type.adoc[]
====

In this example we declare the "dateString" field to be a [classname]+DateType+.
[classname]+DateType+ maintains the value of the field as a [classname]+long+
internally, but if a [classname]+String+ is set or requested, it will be
converted using the given [classname]+SimpleDateFormat+ [classname]+String+
against the given [classname]+TimeZone+.

In the case of a [classname]+TextDelimited+ CSV file, where one column is a date
value, [classname]+DateType+ can be used to declare its format allowing
[classname]+TextDelimited+ to read and write the value as a [classname]+String+,
but use the value internally (in the Tuple) as a [classname]+long+, which is
much more efficient.
