:toc2:
:doctitle: {_doctitle} - Field Sets

[[field-algebra]]
= Field Sets

Cascading applications can perform complex manipulation or "field
algebra" on the fields stored in tuples, using _Fields sets_, a feature of the
[classname]+Fields+ class that provides a sort of wildcard
tool for referencing sets of field values.

These predefined Fields sets are constant values on the
[classname]+Fields+ class. They can be used in many places
where the [classname]+Fields+ class is expected. They are:
Fields.ALL::
include::algebra-all.adoc[]
The [classname]+cascading.tuple.Fields.ALL+
constant is a wildcard that represents all the current available
fields.



Fields.RESULTS::
include::algebra-results.adoc[]
The [classname]+cascading.tuple.Fields.RESULTS+
constant is used to represent the field names of the current
operations return values. This Fields set may only be used as an
output selector on a pipe, causing the pipe to output a tuple
containing the operation results.



Fields.REPLACE::
include::algebra-replace.adoc[]
The [classname]+cascading.tuple.Fields.REPLACE+
constant is used as an output selector to inline-replace values
in the incoming tuple with the results of an operation. This
convenient Fields set allows operations to overwrite the value
stored in the specified field. The current operation must either
specify the identical argument selector field names used by the
pipe, or use the [classname]+ARGS+ Fields set.



Fields.SWAP::
include::algebra-swap.adoc[]
The [classname]+cascading.tuple.Fields.SWAP+
constant is used as an output selector to swap the operation
arguments with its results. Neither the argument and result
field names, nor the size, need to be the same. This is useful
for when the operation arguments are no longer necessary and the
result Fields and values should be appended to the remainder of
the input field names and Tuple.



Fields.ARGS::
include::algebra-replace.adoc[]
The [classname]+cascading.tuple.Fields.ARGS+
constant is used to let a given operation inherit the field
names of its argument Tuple. This Fields set is a convenience
and is typically used when the Pipe output selector is
[classname]+RESULTS+ or
[classname]+REPLACE+. It is specifically used by the
Identity Function when coercing values from Strings to primitive
types.



Fields.GROUP::
include::algebra-group.adoc[]
The [classname]+cascading.tuple.Fields.GROUP+
constant represents all the fields used as grouping key in the
most recent grouping. If no previous grouping exists in the pipe
assembly, [classname]+GROUP+ represents all the
current field names.



Fields.VALUES::
include::algebra-values.adoc[]
The [classname]+cascading.tuple.Fields.VALUES+
constant represents all the fields not used as grouping fields
in a previous Group. That is, if you have fields "a", "b", and
"c", and group on "a", [classname]+Fields.VALUES+ will
resolve to "b" and "c".



Fields.UNKNOWN::
include::algebra-unknown.adoc[]
The [classname]+cascading.tuple.Fields.UNKNOWN+
constant is used when Fields must be declared, but it's not
known how many fields or what their names are. This allows for
processing tuples of arbitrary length from an input source or
some operation. Use this Fields set with caution.



Fields.NONE::
include::algebra-none.adoc[]
The [classname]+cascading.tuple.Fields.NONE+
constant is used to specify no fields. Typically used as an
argument selector for Operations that do not process any Tuples,
like [classname]+cascading.operation.Insert+.



 The chart below shows common ways to merge input and
result fields for the desired output fields. A few minutes with this
chart may help clarify the discussion of fields, tuples, and pipes. Also
see <<each-every>> for details on the different columns
and their relationships to the [classname]+Each+ and
[classname]+Every+ pipes and Functions, Aggregators, and
Buffers.

image:images/field-algebra.svg[align="center"]



