:toc2:
:doctitle: {_doctitle} - Local Platform

[[local-platform]]
== Local Platform

[[building]]
=== Building an Application

The Cascading local mode has no special requirements for building outside the
requirement for any Java application to be executed from the command line.
However, there are two top-level dependencies that should be added to the build
file:

cascading-core-3.x.y.jar::

This JAR contains the Cascading Core class files.

cascading-local-3.x.y.jar::

This JAR contains the Cascading local-mode class files.

[[executing]]
=== Executing an Application

After completing a build of the application's "main" class, the application can
be run like any other Java-based command-line application.

[[source-sink]]
=== Source and Sink Taps

==== Taps

The Cascading local mode only provides a single platform specific
[classname]+Tap+ type:

FileTap::

The [classname]+cascading.tap.local.FileTap+ tap is used with the Cascading
local platform to access files on the local filesystem.

[[debugging]]
=== Troubleshooting and Debugging

IDE debugging and testing in Cascading local mode, unlike Cascading on other
platforms, is straightforward as all the processing happens in the local JVM and
in local memory. Therefore, the first recommendation for debugging Cascading
applications on a given platform is to first write tests that run in Cascading
local mode.

NOTE: Because Cascading local mode runs entirely in memory, large data sets may
cause an OutOfMemoryException. Also, be sure to adjust the Java runtime memory
settings.

In addition to using an IDE debugger, you can use two Cascading features to help
sort out runtime issues.

One feature is the [classname]+Debug+ filter. Best practice is to sprinkle
[classname]+Debug+ operators (see <<ch16-operations.adoc#debug-function, Debug
Function>>) in the pipe assembly and rely on the planner to remove them at
runtime by setting a [classname]+DebugLevel+.

[classname]+Debug+ can only print to the local console via standard output or
standard error. This print limitation makes it harder to use [classname]+Debug+
on distributed platforms, as operations do not execute locally but on the
cluster side. [classname]+Debug+ provides the option to print the current field
names, and a prefix can be set to help distinguish between instances of the
[classname]+Debug+ operation.

Additionally, the actual execution plan for a Flow can be written (and
visualized) via the [methodname]+Flow.writeDOT()+ method. DOT files are simply
text representations of graph data and can be read by tools like Graphviz and
OmniGraffle.

In Cascading local mode, these execution plans are exactly as the pipe
assemblies were coded, except the subassemblies are unwound and the field names
across the Flow are resolved by the planner. In other words, [code]+Fields.ALL+
and other wild cards are converted to the actual field names or ordinals.

If the [methodname]+connect()+ method on the current [classname]+FlowConnector+
fails, the resulting [classname]+PlannerException+ has a
[methodname]+writeDOT()+ method that shows the progress of the current planner.

For planner-related errors that appear during runtime when executing a Flow, see
the chapter on the <<ch21-query-process-planner.adoc#process-planner, Cascading
Process Planner>>.
