:toc2:
:doctitle: {_doctitle} - Apache Tez Platform

[[tez-platform]]
== Apache Tez Platform

Outside of the details provided in the chapter on
<<ch10-hadoop-common.adoc#apache-hadoop,Apache Hadoop>>, the remainder of this
chapter provided details specific to the Apache Tez platform.

=== Configuring Applications

During runtime, Hadoop must be told which application jar file should be pushed
to the cluster

In order to remain platform independent, the [classname]+AppProps+ class should
be used as described in <<ch10-hadoop-common.adoc#configuring,Configuring
Applications>>.

[[building]]
=== Building

Cascading ships with several jars and dependencies in the download archive.

Alternatively, Cascading is available over Maven and Ivy through the Conjars
repository, along with a number of other Cascading-related projects. See
http://conjars.org for more information.

The Cascading Hadoop artifacts include the following:

[code]+cascading-core-3.x.y.jar+::

This jar contains the Cascading Core class files. It should be packaged with
+lib/*.jar+ when using Hadoop.

[code]+cascading-hadoop2-tez-3.x.y.jar+::

This jar contains the Cascading Hadoop 2 and Apache Tez specific dependencies.
It should be packaged with +lib/*.jar+ when using Hadoop.

Cascading works with either of the Hadoop processing modes - the default local
standalone mode and the distributed cluster mode. As specified in the Hadoop
documentation, running in cluster mode requires the creation of a Hadoop job jar
that includes the Cascading jars, plus any needed third-party jars, in its +lib+
directory. This is true regardless of whether they are Cascading Hadoop-mode
applications or raw Apache Tez applications.
