:toc2:
:doctitle: {_doctitle} - Apache Tez Platform

[[tez-platform]]
== Apache Tez Platform

Outside of the details provided in the chapter on
<<ch10-hadoop-common.adoc#apache-hadoop,Apache Hadoop>>, the remainder of this
chapter provided details specific to the Apache Tez platform.

The most up to date information on running Apache Tez and supported Tez releases
can be found in the git repo README:

Released Source::
  https://github.com/cascading/cascading/tree/3.0/cascading-hadoop2-tez

Work In Progress Source::
  https://github.com/cwensel/cascading/tree/wip-3.0/cascading-hadoop2-tez

It should be noted the model behind Apache Tez is much improved over MapReduce.

Some of the benefits include:

* no more ‘identity mappers’ - mappers that simply forward data to the reducer
* support for multiple outputs
* no prefixing data with join ordinality
* suppressing sorting when not needed
* removing HDFS as an intermediate store between jobs

=== Configuring Applications

During runtime, Hadoop must be told which application jar file should be pushed
to the cluster

In order to remain platform independent, the [classname]+AppProps+ class should
be used as described in <<ch10-hadoop-common.adoc#configuring,Configuring
Applications>>.

[[building]]
=== Building

Cascading ships with several jars and dependencies in the download archive.

Alternatively, Cascading is available over Maven and Ivy through the Conjars
repository, along with a number of other Cascading-related projects. See
http://conjars.org for more information.

The Cascading Hadoop artifacts include the following:

[code]+cascading-core-3.x.y.jar+::

This jar contains the Cascading Core class files. It should be packaged with
+lib/*.jar+ when using Hadoop.

[code]+cascading-hadoop2-tez-3.x.y.jar+::

This jar contains the Cascading Hadoop 2 and Apache Tez specific dependencies.
It should be packaged with [code]+lib/*.jar+ when using Hadoop.

Cascading works with either of the Hadoop processing modes - the default local
standalone mode and the distributed cluster mode. As specified in the Hadoop
documentation, running in cluster mode requires the creation of a Hadoop job jar
that includes the Cascading jars, plus any needed third-party jars, in its
[code]+lib+ directory. This is true regardless of whether they are Cascading
Hadoop-mode applications or raw Apache Tez applications.
