:doctitle: {_doctitle} - Built-In SubAssemblies

include::_toc.adoc[]

[[subassemblies]]
== Built-in SubAssemblies

There are a number of helper SubAssemblies provided by the core Cascading
library.

TIP: Many of the assemblies that are described below can be coded to ignore null
values. This allows for an optional but closer resemblance to how similar
functions in SQL perform.

=== Optimized Aggregations

The following SubAssemblies are implementations or optimizations of more
discrete aggregate functions. Many of these SubAssemblies rely on the
[classname]+AggregateBy+ base class, which can be subclassed by developers to
create custom aggregations leveraging the internal partial aggregation
implementation.

[[unique]]
==== Unique

The [classname]+cascading.pipe.assembly.Unique+ SubAssembly is used to remove
duplicate values in a Tuple stream. Uniqueness is determined by the values of
all fields listed in [code]+uniqueFields+. Use [classname]+Fields.ALL+ as the
[code]+uniqueFields+ argument to find all distinct Tuples in a stream.

.Using the Unique SubAssembly
====
include::_subassembly-unique.adoc[]
====

[classname]+Unique+ uses the [classname]+FirstNBuffer+ to more efficiently
determine unique values.

[[aggregate-by]]
==== AggregateBy

The [classname]+cascading.pipe.assembly.AggregateBy+ SubAssembly is an
implementation of the partial aggregation pattern, and is the base class for
built-in and custom partial aggregation implementations like
[classname]+AverageBy+ or [classname]+CountBy+.

Generally the AggregateBy class is used to combine multiple AggregateBy
subclasses into a single Pipe.

.Composing partial aggregations with AggregateBy
====
include::_partials-compose.adoc[]
====

To create a custom partial aggregation, subclass the AggregateBy class and
implement the appropriate internal interfaces. See the Javadoc for details.

[[AverageBy]]
==== AverageBy

The [classname]+cascading.pipe.assembly.AverageBy+ SubAssembly calculates an
average of the given [code]+valueFields+ and returns the result in the
[code]+averageField+ field. AverageBy may be combined with other AggregateBy
subclasses so they may be executed simultaneously over the same grouping.

.Using AverageBy
====
include::_partials-averageby.adoc[]
====

[[CountBy]]
==== CountBy

The [classname]+cascading.pipe.assembly.CountBy+ SubAssembly performs a count
over the given [code]+groupingFields+ and returns the result in the
[code]+countField+ field. CountBy may be combined with other AggregateBy
subclasses so they may be executed simultaneously over the same grouping.

.Using CountBy
====
include::_partials-countby.adoc[]
====

[[SumBy]]
==== SumBy

The [classname]+cascading.pipe.assembly.SumBy+ SubAssembly performs a sum over
the given [code]+valueFields+ and returns the result in the [code]+sumField+
field. SumBy may be combined with other AggregateBy subclasses so that they may
be executed simultaneously over the same grouping.

.Using SumBy
====
include::_partials-sumby.adoc[]
====

==== FirstBy

The [classname]+cascading.pipe.assembly.FirstBy+ SubAssembly is used to return
the first encountered value in the given [code]+valueFields+. FirstBy may be
combined with other AggregateBy subclasses so they may be executed
simultaneously over the same grouping.

.Using FirstBy
====
include::_partials-firstby.adoc[]
====

Note if the [code]+valueFields+ Fields instance has field comparators, they will
be used to sort the order of argument values. Otherwise, the fields will not be
sorted in any deterministic order.

=== Stream Shaping

[[coerce]]
==== Coerce

The [classname]+cascading.pipe.assembly.Coerce+ SubAssembly is used to coerce a
set of values from one type to another type -- for example, to convert the
[code]+age+ field from a [classname]+String+ to an [classname]+Integer+.

.Using Coerce
====
include::_subassembly-coerce.adoc[]
====

[[discard]]
==== Discard

The [classname]+cascading.pipe.assembly.Discard+ SubAssembly is used to shape
the Tuple stream by discarding all fields given on the constructor. All unlisted
fields are retained.

.Using Discard
====
include::_subassembly-discard.adoc[]
====

[[rename]]
==== Rename

The [classname]+cascading.pipe.assembly.Rename+ SubAssembly is used to rename a
field.

.Using Rename
====
include::_subassembly-rename.adoc[]
====

[[retain]]
==== Retain

The [classname]+cascading.pipe.assembly.Retain+ SubAssembly is used to shape the
Tuple stream by retaining all fields given on the constructor. All unlisted
fields are discarded.

.Using Retain
====
include::_subassembly-retain.adoc[]
====
