:toc2:
:doctitle: {_doctitle} - Extending Cascading

== Extending Cascading

=== Scripting

The Cascading API was designed with scripting in mind. Any JVM-compatible
scripting language can import and instantiate Cascading classes, create pipe
assemblies and flows, and execute those flows. And if the scripting language in
question supports Domain Specific Language (DSL) creation, users can create
their own DSLs to handle common idioms.

The Cascading website (http://cascading.org/extensions/) includes information on
scripting language bindings that are publicly available.

[[custom-types]]
=== Custom Types and Serialization

The [classname]+Tuple+ class is a generic container for all
[classname]+java.lang.Object+ instances.

Thus any primitive value or custom Class can be stored in a [classname]+Tuple+
instance - that is, returned by a [classname]+Function+,
[classname]+Aggregator+, or [classname]+Buffer+ as a result value.

Unfortunately there is no common method for managing the serialization of custom
types that is cross platform. Please see the platform specific chapters for
details on registering serializers that Cascading can adopt at runtime.

=== Custom Comparators and Hashing

Frequently, objects in one [classname]+Tuple+ are compared to objects in a
second [classname]+Tuple+. This is especially true during the sort phase of
[classname]+GroupBy+ and [classname]+CoGroup+.

By default, Cascading uses the native [classname]+Object+ methods
[methodname]+equals()+ and [methodname]+hashCode()+ to compare two values and
get a consistent hash code for a given value, respectively.

To override this default behavior, you can create a custom
[classname]+java.util.Comparator+ class to perform comparisons on a given field
in a Tuple. For instance, to secondary-sort a collection of custom
[classname]+Person+ objects in a [classname]+GroupBy+, use the
[code]+Fields.setComparator()+ method to designate the custom
[classname]+Comparator+ to the [classname]+Fields+ instance that specifies the
sort fields.

Alternatively, you can set a default [classname]+Comparator+ to be used by a
[classname]+Flow+, or used locally on a given [classname]+Pipe+ instance. There
are two ways to do this. Call
[code]+FlowProps.setDefaultTupleElementComparator()+ on a
[classname]+Properties+ instance, or use the property key
[code]+cascading.flow.tuple.element.comparator+.

If the hash code must also be customized, the custom Comparator can implement
the interface [classname]+cascading.tuple.Hasher+.

For more information, see the Javadoc.
