:doctitle: {_doctitle} - Cookbook: Code Examples of Cascading Idioms

include::_toc.adoc[]

== Cookbook: Code Examples of Cascading Idioms

This chapter demonstrates some common idioms used in Cascading applications.

=== Tuples and Fields

Copy a Tuple instance::

include::_cookbook-copy.adoc[]

Nest a Tuple instance within a Tuple::

include::_cookbook-nest.adoc[]

Build a longer Fields instance::

include::_cookbook-fieldsappend.adoc[]

Remove a field from a longer Fields instance::

include::_cookbook-fieldssubtract.adoc[]

=== Stream Shaping

Split (branch) a Tuple stream::

include::_cookbook-split.adoc[]

Copy a field value::

include::_cookbook-copyfield.adoc[]

Discard (drop) a field::

include::_cookbook-discardfield.adoc[]

Retain (keep) a field::

include::_cookbook-retainfield.adoc[]

Rename a field::

include::_cookbook-renamefield.adoc[]

Coerce field values from Strings to primitives::

include::_cookbook-coercefields.adoc[]

Insert constant values into a stream::

include::_cookbook-insertvalue.adoc[]

=== Common Operations

Parse a String date/time value::

include::_cookbook-parsedate.adoc[]

Format a timestamp to a date/time value::

include::_cookbook-formatdate.adoc[]

=== Stream Ordering

Remove duplicate tuples in a stream::

include::_cookbook-distinctgroup.adoc[]

Create a list of unique values::

include::_cookbook-distinctvalue.adoc[]

Find first occurrence in time of a unique value::

include::_cookbook-distinctorder.adoc[]

=== API Usage

Pass properties to a custom Operation::

include::_cookbook-passproperties.adoc[]

Bind multiple sources and sinks to a Flow::

include::_cookbook-sourcessinks.adoc[]
