
== What is Apache Hadoop?

From the Hadoop website, it "is a software platform that lets one easily write
and run applications that process vast amounts of data". Hadoop does this by
providing a storage layer that holds vast amounts of data, and an execution
layer that runs an application in parallel across the cluster, using coordinated
subsets of the stored data.

The storage layer, called the Hadoop File System (HDFS), looks like a single
storage volume that has been optimized for many concurrent serialized reads of
large data files - where "large" might be measured in gigabytes or petabytes.
However, it does have limitations. For example, random access to the data is not
really possible in an efficient manner. And Hadoop only supports a single writer
for output. But this limit helps make Hadoop very performant and reliable, in
part because it allows for the data to be replicated across the cluster,
reducing the chance of data loss.

The execution layer, called MapReduce, relies on a divide-and-conquer strategy
to manage massive data sets and computing processes. Explaining MapReduce is
beyond the scope of this document, but its complexity, and the difficulty of
creating real-world applications against it, are the chief driving force behind
the creation of Cascading.

Hadoop, according to its documentation, can be configured to run in three modes:
* standalone mode (i.e., on the local computer, useful for testing and debugging in an IDE), 
* pseudo-distributed mode (i.e., on an emulated "cluster" of one computer, not useful for much), and
* fully-distributed mode (on a full cluster, for staging or production purposes).

The pseudo-distributed mode does not add
value for most purposes, and will not be discussed further. Cascading itself can
run locally or on the Hadoop platform, where Hadoop itself may be in standalone
or distributed mode. The primary difference between these two platforms, local
or Hadoop, is that, when Cascading is running in local mode, it makes no use of
Hadoop APIs and performs all of its work in memory, allowing it to be very fast -
but consequently not as robust or scalable as when it is running on the Hadoop
platform.

Apache Hadoop is an Open Source Apache project and is freely available. It can
be downloaded from the Hadoop website: <<,http://hadoop.apache.org/core/>>

== Hadoop 1 MapReduce vs Hadoop 2 MapReduce

Cascading supports both Hadoop 1.x and 2.x by providing two Java dependencies,
_cascading-hadoop.jar_ and _cascading-hadoop2-mr1.jar_. These dependencies can
be interchanged but the _hadoop2-mr1.jar_ introduces new and deprecates older
API calls where appropriate. It should be pointed out _hadoop1-mr1.jar_ only
supports MapReduce 1 API conventions. With this naming scheme new API
conventions can be introduced without risk of naming collisions on dependencies.
